GLOBAL.TUNING.Spring_factor = GetModConfigData("Spring_factor")
GLOBAL.TUNING.Winter_factor = GetModConfigData("Winter_factor")
GLOBAL.TUNING.Day_factor = GetModConfigData("Day_factor")
GLOBAL.TUNING.Dusk_factor = GetModConfigData("Dusk_factor")
GLOBAL.TUNING.Night_factor = GetModConfigData("Night_factor")
